### ISSUE TITLE
Is there any javascirpt lib like "bitcoinJS" in ETH?

### ISSUE THREAD

**Issue by byenic** [Orangem21/Solidity#1]
Hey, thanks for your example of the ETH.
As the title, do you know is there any ETH transaction protocol based on javascript library just like the BitcoinJS?

Thanks very much!

**Comment by Orangem21** [comment]
Ethereum is working on a new smart contract language for JS.

**Comment by byenic** [comment]
OK. Thx for the response! Do you means the solidity @Orangem21 for example, I want to develop an eth wallet on iOS, which library should I import?

**Comment by Orangem21** [comment]
web3.js

2018-01-16 20:47 GMT+08:00 byenic <notifications@github.com>:

**Comment by byenic** [comment]
Thanks very much!
